name: GitHub Actions Demo 
run-name: ${{ github.actor }} đang thử nghiệm GitHub Actions 🚀 
trên: [push] 
jobs: 
  Explore-GitHub-Actions: 
    run-on: ubuntu-lateststeps 
    : 
      - run: echo " 🎉 Công việc được tự động kích hoạt bởi sự kiện ${{ github.event_name }}." 
      - run: echo "🐧 Công việc này hiện đang chạy trên máy chủ ${{runner.os }} do GitHub lưu trữ!" 
      - run: echo "🔎 Tên nhánh của bạn là ${{ github.ref }} và kho lưu trữ của bạn là ${{ github.repository }}." 
      - tên: Kiểm tra 
        việc sử dụng mã kho lưu trữ: actions/checkout@v4 
      - run: echo "💡 Kho lưu trữ ${{ github.repository }} đã được sao chép vào trình chạy." 
      - run: echo "🖥️ Quy trình làm việc hiện đã sẵn sàng để kiểm tra mã của bạn trên trình chạy." 
      - name: Liệt kê các file trong kho 
        chạy: | 
          ls ${{ github.workspace }} 
      - run: echo "🍏 Trạng thái của công việc này là ${{ job.status }}."
